setwd("C:\\Users\\SZXP0196\\Desktop\\Rdata")
consumptionraw<-read.table("household_power_consumption.txt",header=TRUE,sep=";",stringsAsFactors=FALSE, dec=".")
consumption<-consumptionraw[consumptionraw$Date=="1/2/2007"|consumptionraw$Date=="2/2/2007",]
consumption$Global_active_power<-as.numeric(consumption$Global_active_power)
consumption$Global_reactive_power<-as.numeric(consumption$Global_reactive_power)
consumption$Voltage<-as.numeric(consumption$Voltage)
consumption$Sub_metering_1<-as.numeric(consumption$Sub_metering_1)
consumption$Sub_metering_2<-as.numeric(consumption$Sub_metering_2)
consumption$Sub_metering_3<-as.numeric(consumption$Sub_metering_3)
consumption$datetime<-strptime(paste(consumption$Date, consumption$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png(file="plot4.png",height=480,width=(480))
par(mfrow=c(2,2))
plot(consumption$datetime,consumption$Global_active_power,ylab="Global Active Power",type="l")
plot(consumption$datetime,consumption$Voltage,ylab="Vlotage",xlab="datetime",type="l")
plot(consumption$datetime,as.numeric(consumption$Sub_metering_1),main = "",ylab="Energy Sub Metering",xlab="",type="l",col="black")
lines(consumption$datetime,consumption$Sub_metering_2,col="red")
lines(consumption$datetime,consumption$Sub_metering_3,col="blue")
legend("topright",cex=0.3, lty = 1, col = c(1,2,4), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(consumption$datetime,consumption$Global_reactive_power,xlab="datetime",type="l")
dev.off()